const questionsBank = {
  easy: [
    {q:"2 + 3 = ?", options:["4","5","6","7"], answer:"5"},
    {q:"What color is the sky on a clear day?", options:["Blue","Green","Red","Yellow"], answer:"Blue"},
    {q:"5 - 2 = ?", options:["2","3","4","5"], answer:"3"},
    {q:"Which is an animal?", options:["Car","Dog","Chair","Book"], answer:"Dog"},
    {q:"What comes after 9?", options:["8","9","10","11"], answer:"10"},
    {q:"How many legs does a spider have?", options:["6","7","8","9"], answer:"8"},
    {q:"Which shape has four equal sides?", options:["Rectangle","Circle","Triangle","Square"], answer:"Square"},
    {q:"Which is a fruit?", options:["Banana","Potato","Bread","Carrot"], answer:"Banana"},
    {q:"1 + 1 = ?", options:["1","2","3","4"], answer:"2"},
    {q:"What sound does a cat make?", options:["Bark","Moo","Meow","Neigh"], answer:"Meow"},
    {q:"How many days are in a week?", options:["5","6","7","8"], answer:"7"},
    {q:"Which is used to write on paper?", options:["Spoon","Pen","Plate","Shoe"], answer:"Pen"},
    {q:"Which object tells time?", options:["Clock","Pillow","Window","Shoe"], answer:"Clock"},
    {q:"Which color do you get by mixing red and white?", options:["Purple","Pink","Brown","Black"], answer:"Pink"},
    {q:"Count: 3 + 4 = ?", options:["5","6","7","8"], answer:"7"},
    {q:"Which is a baby cat called?", options:["Puppy","Calf","Kitten","Foal"], answer:"Kitten"},
    {q:"Which month comes after March?", options:["April","May","June","February"], answer:"April"},
    {q:"Which item do you wear on your feet?", options:["Hat","Socks","Glasses","Watch"], answer:"Socks"},
    {q:"What color is a ripe banana?", options:["Green","Blue","Yellow","Red"], answer:"Yellow"},
    {q:"Which shape is round?", options:["Square","Triangle","Circle","Rectangle"], answer:"Circle"}
  ],
  medium: [
    {q:"10 × 2 = ?", options:["10","20","30","40"], answer:"20"},
    {q:"Which planet is known as the Red Planet?", options:["Venus","Mars","Jupiter","Saturn"], answer:"Mars"},
    {q:"What does HTML stand for?", options:["HyperText Markup Language","HighText Markup Language","Hyperlink Make Language","HyperText Make Language"], answer:"HyperText Markup Language"},
    {q:"12 ÷ 3 = ?", options:["2","3","4","5"], answer:"4"},
    {q:"Which shape has three sides?", options:["Square","Circle","Triangle","Rectangle"], answer:"Triangle"},
    {q:"Find the next number: 2, 4, 6, ?", options:["7","8","9","10"], answer:"8"},
    {q:"Which is a programming language?", options:["HTML","CSS","Python","HTTP"], answer:"Python"},
    {q:"If you flip a coin, possible outcomes are:", options:["Heads/Tails","Red/Blue","Even/Odd","Up/Down"], answer:"Heads/Tails"},
    {q:"If 5x = 20, x = ?", options:["2","3","4","5"], answer:"4"},
    {q:"Which is a mammal?", options:["Shark","Dolphin","Octopus","Crocodile"], answer:"Dolphin"},
    {q:"Opposite of 'hot'?", options:["Warm","Cold","Cool","Heat"], answer:"Cold"},
    {q:"Which number is prime?", options:["12","13","14","15"], answer:"13"},
    {q:"What is 15 - 7?", options:["6","7","8","9"], answer:"8"},
    {q:"Which tool is used to measure temperature?", options:["Ruler","Thermometer","Scale","Compass"], answer:"Thermometer"},
    {q:"What comes next: A, C, E, G, ?", options:["H","I","J","K"], answer:"I"},
    {q:"Which ocean is the largest?", options:["Atlantic","Indian","Arctic","Pacific"], answer:"Pacific"},
    {q:"Which gas do plants need for photosynthesis?", options:["Oxygen","Nitrogen","Carbon Dioxide","Helium"], answer:"Carbon Dioxide"},
    {q:"If a train leaves at 2pm and arrives at 4pm, travel time is:", options:["1 hour","2 hours","3 hours","4 hours"], answer:"2 hours"},
    {q:"Which is a continent?", options:["France","Asia","Texas","Madrid"], answer:"Asia"},
    {q:"Which shape has opposite sides equal and four right angles?", options:["Square","Rhombus","Parallelogram","Trapezoid"], answer:"Square"}
  ],
  hard: [
    {q:"Solve: (15 - 5) ÷ 2 = ?", options:["4","5","6","7"], answer:"5"},
    {q:"If f(x)=2x+3, then f^{-1}(7) = ?", options:["1","2","3","4"], answer:"2"},
    {q:"Which protocol secures web browsing?", options:["FTP","HTTP","SMTP","HTTPS"], answer:"HTTPS"},
    {q:"Find the odd one out: Dog, Cat, Apple, Cow", options:["Dog","Cat","Apple","Cow"], answer:"Apple"},
    {q:"Next in sequence: 3, 9, 27, ?", options:["54","72","81","243"], answer:"81"},
    {q:"If all roses are flowers and some flowers fade quickly, what can be inferred?", options:["All roses fade quickly","Some flowers are roses","Some roses fade quickly","None"], answer:"Some flowers are roses"},
    {q:"What is the capital of Canada?", options:["Toronto","Vancouver","Ottawa","Montreal"], answer:"Ottawa"},
    {q:"What number makes the equation true: 7x = 56 ?", options:["6","7","8","9"], answer:"8"},
    {q:"Which is a prime number?", options:["21","22","23","24"], answer:"23"},
    {q:"If you roll two dice, probability of getting 2 sixes is:", options:["1/6","1/36","1/12","1/18"], answer:"1/36"},
    {q:"Complete analogy: Finger is to Hand as Leaf is to ?", options:["Tree","Branch","Root","Seed"], answer:"Tree"},
    {q:"Which term means 'study of the mind'?", options:["Biology","Psychology","Sociology","Geology"], answer:"Psychology"},
    {q:"Simplify: 4(2x + 3) = ?", options:["8x + 3","8x + 12","6x + 12","8x + 6"], answer:"8x + 12"},
    {q:"Which scientist proposed gravity law?", options:["Einstein","Newton","Galileo","Bohr"], answer:"Newton"},
    {q:"Find the missing number: 11, 13, 17, 19, ?", options:["21","22","23","24"], answer:"23"},
    {q:"Which is an example of renewable energy?", options:["Coal","Oil","Solar","Gas"], answer:"Solar"},
    {q:"If x^2 = 49, x = ?", options:["6","7","-7","Both 7 and -7"], answer:"Both 7 and -7"},
    {q:"Which country uses the Yen?", options:["China","South Korea","Japan","Thailand"], answer:"Japan"},
    {q:"If A>B and B>C then which is true?", options:["A>C","C>A","A=B","B>A"], answer:"A>C"},
    {q:"What is 17 + 13?", options:["29","30","31","32"], answer:"30"}
  ]
};
